package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrGroupUser generated by hbm2java
 */
@Entity
@Table(name = "flickr_group_user", schema = "public")
public class FlickrGroupUser implements java.io.Serializable {

	private long groupUserId;
	private FlickrUser flickrUser;
	private long groupId;
	private Date groupUserCreatedDate;

	public FlickrGroupUser() {
	}

	public FlickrGroupUser(long groupUserId, FlickrUser flickrUser,
			long groupId, Date groupUserCreatedDate) {
		this.groupUserId = groupUserId;
		this.flickrUser = flickrUser;
		this.groupId = groupId;
		this.groupUserCreatedDate = groupUserCreatedDate;
	}

	@Id
	@Column(name = "group_user_id", unique = true, nullable = false)
	public long getGroupUserId() {
		return this.groupUserId;
	}

	public void setGroupUserId(long groupUserId) {
		this.groupUserId = groupUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public FlickrUser getFlickrUser() {
		return this.flickrUser;
	}

	public void setFlickrUser(FlickrUser flickrUser) {
		this.flickrUser = flickrUser;
	}

	@Column(name = "group_id", nullable = false)
	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "group_user_created_date", nullable = false, length = 29)
	public Date getGroupUserCreatedDate() {
		return this.groupUserCreatedDate;
	}

	public void setGroupUserCreatedDate(Date groupUserCreatedDate) {
		this.groupUserCreatedDate = groupUserCreatedDate;
	}

}
