package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrImageRating generated by hbm2java
 */
@Entity
@Table(name = "flickr_image_rating", schema = "public")
public class FlickrImageRating implements java.io.Serializable {

	private long imageRatingId;
	private FlickrImage flickrImage;
	private int ratingNumber;
	private long userId;
	private Date ratingCreatedDate;

	public FlickrImageRating() {
	}

	public FlickrImageRating(long imageRatingId, FlickrImage flickrImage,
			int ratingNumber, long userId, Date ratingCreatedDate) {
		this.imageRatingId = imageRatingId;
		this.flickrImage = flickrImage;
		this.ratingNumber = ratingNumber;
		this.userId = userId;
		this.ratingCreatedDate = ratingCreatedDate;
	}

	@Id
	@Column(name = "image_rating_id", unique = true, nullable = false)
	public long getImageRatingId() {
		return this.imageRatingId;
	}

	public void setImageRatingId(long imageRatingId) {
		this.imageRatingId = imageRatingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", nullable = false)
	public FlickrImage getFlickrImage() {
		return this.flickrImage;
	}

	public void setFlickrImage(FlickrImage flickrImage) {
		this.flickrImage = flickrImage;
	}

	@Column(name = "rating_number", nullable = false)
	public int getRatingNumber() {
		return this.ratingNumber;
	}

	public void setRatingNumber(int ratingNumber) {
		this.ratingNumber = ratingNumber;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rating_created_date", nullable = false, length = 29)
	public Date getRatingCreatedDate() {
		return this.ratingCreatedDate;
	}

	public void setRatingCreatedDate(Date ratingCreatedDate) {
		this.ratingCreatedDate = ratingCreatedDate;
	}

}
