package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrImageData generated by hbm2java
 */
@Entity
@Table(name = "flickr_image_data", schema = "public")
public class FlickrImageData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6816080786364448136L;
	private long imageDataId;
	private FlickrImage flickrImage;
	private byte[] imageBytes;
	private Date imageDataCreatedDate;

	public FlickrImageData() {
	}

	public FlickrImageData(long imageDataId, FlickrImage flickrImage,
			byte[] imageBytes, Date imageDataCreatedDate) {
		this.imageDataId = imageDataId;
		this.flickrImage = flickrImage;
		this.imageBytes = imageBytes;
		this.imageDataCreatedDate = imageDataCreatedDate;
	}

	@Id
	@Column(name = "image_data_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public long getImageDataId() {
		return this.imageDataId;
	}

	public void setImageDataId(long imageDataId) {
		this.imageDataId = imageDataId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", nullable = false)
	public FlickrImage getFlickrImage() {
		return this.flickrImage;
	}

	public void setFlickrImage(FlickrImage flickrImage) {
		this.flickrImage = flickrImage;
	}

	@Column(name = "image_bytes", nullable = false)
	public byte[] getImageBytes() {
		return this.imageBytes;
	}

	public void setImageBytes(byte[] imageBytes) {
		this.imageBytes = imageBytes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "image_data_created_date", nullable = false, length = 29)
	public Date getImageDataCreatedDate() {
		return this.imageDataCreatedDate;
	}

	public void setImageDataCreatedDate(Date imageDataCreatedDate) {
		this.imageDataCreatedDate = imageDataCreatedDate;
	}

}
