package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrGroup generated by hbm2java
 */
@Entity
@Table(name = "flickr_group", schema = "public")
public class FlickrGroup implements java.io.Serializable {

	private long groupId;
	private String groupName;
	private String groupDescription;
	private long groupOwnerUserId;
	private Date groupCreatedDate;

	public FlickrGroup() {
	}

	public FlickrGroup(long groupId, String groupName, String groupDescription,
			long groupOwnerUserId, Date groupCreatedDate) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.groupDescription = groupDescription;
		this.groupOwnerUserId = groupOwnerUserId;
		this.groupCreatedDate = groupCreatedDate;
	}

	@Id
	@Column(name = "group_id", unique = true, nullable = false)
	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_name", nullable = false, length = 1000)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "group_description", nullable = false, length = 1000)
	public String getGroupDescription() {
		return this.groupDescription;
	}

	public void setGroupDescription(String groupDescription) {
		this.groupDescription = groupDescription;
	}

	@Column(name = "group_owner_user_id", nullable = false)
	public long getGroupOwnerUserId() {
		return this.groupOwnerUserId;
	}

	public void setGroupOwnerUserId(long groupOwnerUserId) {
		this.groupOwnerUserId = groupOwnerUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "group_created_date", nullable = false, length = 29)
	public Date getGroupCreatedDate() {
		return this.groupCreatedDate;
	}

	public void setGroupCreatedDate(Date groupCreatedDate) {
		this.groupCreatedDate = groupCreatedDate;
	}

}
