package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrGroupAlbumAccess generated by hbm2java
 */
@Entity
@Table(name = "flickr_group_album_access", schema = "public")
public class FlickrGroupAlbumAccess implements java.io.Serializable {

	private long groupAlbumAccessId;
	private FlickrAlbum flickrAlbum;
	private long groupId;
	private Date groupAlbumAccessCreatedDate;

	public FlickrGroupAlbumAccess() {
	}

	public FlickrGroupAlbumAccess(long groupAlbumAccessId,
			FlickrAlbum flickrAlbum, long groupId,
			Date groupAlbumAccessCreatedDate) {
		this.groupAlbumAccessId = groupAlbumAccessId;
		this.flickrAlbum = flickrAlbum;
		this.groupId = groupId;
		this.groupAlbumAccessCreatedDate = groupAlbumAccessCreatedDate;
	}

	@Id
	@Column(name = "group_album_access_id", unique = true, nullable = false)
	public long getGroupAlbumAccessId() {
		return this.groupAlbumAccessId;
	}

	public void setGroupAlbumAccessId(long groupAlbumAccessId) {
		this.groupAlbumAccessId = groupAlbumAccessId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "album_id", nullable = false)
	public FlickrAlbum getFlickrAlbum() {
		return this.flickrAlbum;
	}

	public void setFlickrAlbum(FlickrAlbum flickrAlbum) {
		this.flickrAlbum = flickrAlbum;
	}

	@Column(name = "group_id", nullable = false)
	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "group_album_access_created_date", nullable = false, length = 29)
	public Date getGroupAlbumAccessCreatedDate() {
		return this.groupAlbumAccessCreatedDate;
	}

	public void setGroupAlbumAccessCreatedDate(Date groupAlbumAccessCreatedDate) {
		this.groupAlbumAccessCreatedDate = groupAlbumAccessCreatedDate;
	}

}
