package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrUserRole generated by hbm2java
 */
@Entity
@Table(name = "flickr_user_role", schema = "public")
public class FlickrUserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1022779110992156328L;
	private long userRoleId;
	private FlickrUser flickrUser;
	private String userRoleUsername;
	private String userRoleRole;
	private Date userRoleCreatedDate;
	private Date userRoleUpdatedDate;

	public FlickrUserRole() {
	}

	public FlickrUserRole(long userRoleId, FlickrUser flickrUser,
			String userRoleUsername, String userRoleRole,
			Date userRoleCreatedDate, Date userRoleUpdatedDate) {
		this.userRoleId = userRoleId;
		this.flickrUser = flickrUser;
		this.userRoleUsername = userRoleUsername;
		this.userRoleRole = userRoleRole;
		this.userRoleCreatedDate = userRoleCreatedDate;
		this.userRoleUpdatedDate = userRoleUpdatedDate;
	}

	@Id
	@Column(name = "user_role_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public FlickrUser getFlickrUser() {
		return this.flickrUser;
	}

	public void setFlickrUser(FlickrUser flickrUser) {
		this.flickrUser = flickrUser;
	}

	@Column(name = "user_role_username", nullable = false, length = 50)
	public String getUserRoleUsername() {
		return this.userRoleUsername;
	}

	public void setUserRoleUsername(String userRoleUsername) {
		this.userRoleUsername = userRoleUsername;
	}

	@Column(name = "user_role_role", nullable = false, length = 50)
	public String getUserRoleRole() {
		return this.userRoleRole;
	}

	public void setUserRoleRole(String userRoleRole) {
		this.userRoleRole = userRoleRole;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_role_created_date", nullable = false, length = 29)
	public Date getUserRoleCreatedDate() {
		return this.userRoleCreatedDate;
	}

	public void setUserRoleCreatedDate(Date userRoleCreatedDate) {
		this.userRoleCreatedDate = userRoleCreatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_role_updated_date", nullable = false, length = 29)
	public Date getUserRoleUpdatedDate() {
		return this.userRoleUpdatedDate;
	}

	public void setUserRoleUpdatedDate(Date userRoleUpdatedDate) {
		this.userRoleUpdatedDate = userRoleUpdatedDate;
	}

}
