package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrFavourites generated by hbm2java
 */
@Entity
@Table(name = "flickr_favourites", schema = "public")
public class FlickrFavourites implements java.io.Serializable {

	private long favouritesId;
	private FlickrImage flickrImage;
	private FlickrUser flickrUser;
	private Date favouritesCreatedDate;

	public FlickrFavourites() {
	}

	public FlickrFavourites(long favouritesId, FlickrImage flickrImage,
			FlickrUser flickrUser, Date favouritesCreatedDate) {
		this.favouritesId = favouritesId;
		this.flickrImage = flickrImage;
		this.flickrUser = flickrUser;
		this.favouritesCreatedDate = favouritesCreatedDate;
	}

	@Id
	@Column(name = "favourites_id", unique = true, nullable = false)
	public long getFavouritesId() {
		return this.favouritesId;
	}

	public void setFavouritesId(long favouritesId) {
		this.favouritesId = favouritesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", nullable = false)
	public FlickrImage getFlickrImage() {
		return this.flickrImage;
	}

	public void setFlickrImage(FlickrImage flickrImage) {
		this.flickrImage = flickrImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public FlickrUser getFlickrUser() {
		return this.flickrUser;
	}

	public void setFlickrUser(FlickrUser flickrUser) {
		this.flickrUser = flickrUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "favourites_created_date", nullable = false, length = 29)
	public Date getFavouritesCreatedDate() {
		return this.favouritesCreatedDate;
	}

	public void setFavouritesCreatedDate(Date favouritesCreatedDate) {
		this.favouritesCreatedDate = favouritesCreatedDate;
	}

}
