package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrImageMetadata generated by hbm2java
 */

@Entity
@Table(name = "flickr_image_metadata", schema = "public")
public class FlickrImageMetadata implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8464474641043032088L;
	private long imageMetadataId;
	private FlickrImage flickrImage;
	private String propertyName;
	private String propertyValue;
	private Date imageMetadataCreatedDate;

	public FlickrImageMetadata() {
	}

	public FlickrImageMetadata(long imageMetadataId, FlickrImage flickrImage,
			String propertyName, String propertyValue,
			Date imageMetadataCreatedDate) {
		this.imageMetadataId = imageMetadataId;
		this.flickrImage = flickrImage;
		this.propertyName = propertyName;
		this.propertyValue = propertyValue;
		this.imageMetadataCreatedDate = imageMetadataCreatedDate;
	}

	@Id
	@Column(name = "image_metadata_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public long getImageMetadataId() {
		return this.imageMetadataId;
	}

	public void setImageMetadataId(long imageMetadataId) {
		this.imageMetadataId = imageMetadataId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id", nullable = false)
	public FlickrImage getFlickrImage() {
		return this.flickrImage;
	}

	public void setFlickrImage(FlickrImage flickrImage) {
		this.flickrImage = flickrImage;
	}

	@Column(name = "property_name", nullable = false, length = 1000)
	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	@Column(name = "property_value", nullable = false, length = 1000)
	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "image_metadata_created_date", nullable = false, length = 29)
	public Date getImageMetadataCreatedDate() {
		return this.imageMetadataCreatedDate;
	}

	public void setImageMetadataCreatedDate(Date imageMetadataCreatedDate) {
		this.imageMetadataCreatedDate = imageMetadataCreatedDate;
	}

}
