package com.xlickr.hibernate.entities;

// Generated Jul 17, 2015 9:25:23 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FlickrFriends generated by hbm2java
 */
@Entity
@Table(name = "flickr_friends", schema = "public")
public class FlickrFriends implements java.io.Serializable {

	private long friendsId;
	private FlickrUser flickrUser;
	private long friendUserId;
	private Date friendCreatedDate;

	public FlickrFriends() {
	}

	public FlickrFriends(long friendsId, FlickrUser flickrUser,
			long friendUserId, Date friendCreatedDate) {
		this.friendsId = friendsId;
		this.flickrUser = flickrUser;
		this.friendUserId = friendUserId;
		this.friendCreatedDate = friendCreatedDate;
	}

	@Id
	@Column(name = "friends_id", unique = true, nullable = false)
	public long getFriendsId() {
		return this.friendsId;
	}

	public void setFriendsId(long friendsId) {
		this.friendsId = friendsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "my_user_id", nullable = false)
	public FlickrUser getFlickrUser() {
		return this.flickrUser;
	}

	public void setFlickrUser(FlickrUser flickrUser) {
		this.flickrUser = flickrUser;
	}

	@Column(name = "friend_user_id", nullable = false)
	public long getFriendUserId() {
		return this.friendUserId;
	}

	public void setFriendUserId(long friendUserId) {
		this.friendUserId = friendUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "friend_created_date", nullable = false, length = 29)
	public Date getFriendCreatedDate() {
		return this.friendCreatedDate;
	}

	public void setFriendCreatedDate(Date friendCreatedDate) {
		this.friendCreatedDate = friendCreatedDate;
	}

}
